[package]
name = "task-board"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
anyhow = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }

[dependencies]
anyhow = "1.0"
rocket = "0.4"
rust-embed="5.5"
